# Generated by Django 5.0.6 on 2024-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cod',
        ),
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.CharField(default=1, help_text='Ten en cuenta que al cambiar el cédula,\n        ese sería con el que ingresarías a la plataforma.', max_length=100, unique=True, verbose_name='Cédula'),
            preserve_default=False,
        ),
    ]
