# Generated by Django 5.0.6 on 2024-10-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_cod_user_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(max_length=1000, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('video', models.CharField(verbose_name='video')),
                ('comment', models.TextField(max_length=1000, verbose_name='Comentario')),
            ],
        ),
    ]
