# Generated by Django 5.0.6 on 2024-10-11 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_evento_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='user',
        ),
        migrations.CreateModel(
            name='EventoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
