# Generated by Django 5.0.6 on 2024-10-14 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image_evento_imagen_remove_evento_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Actualización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventousuario',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventousuario',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Actualización'),
            preserve_default=False,
        ),
    ]
